[package]
name = "VarAntAnno"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
dioxus = "0.6.3"
dioxus-router = "0.6.3"
dioxus-ssr = "0.6.2"
rayon = "1.10.0"
serde = "1.0.219"
serde_json = "1.0.140"
sonic-rs = "0.4.1"
