[package]
name = "genovaranno"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
cmd_lib = "1.9.5"
dotenv = "0.15.0"
rayon = "1.10.0"
serde = "1.0.219"
serde_json = "1.0.140"
